import { writeFileSync } from 'node:fs'

const USER = process.env.GITHUB_USER ?? 'adetxt'
const API = 'https://api.github.com'

const headers = {
  'User-Agent': 'adetxt-portfolio-sync',
  Accept: 'application/vnd.github+json',
}
if (process.env.SYNC_GITHUB_TOKEN) {
  headers.Authorization = `Bearer ${process.env.SYNC_GITHUB_TOKEN}`
}

async function fetchRepos() {
  const res = await fetch(
    `${API}/users/${USER}/repos?per_page=100&sort=updated&type=owner`,
    { headers },
  )
  if (!res.ok) {
    throw new Error(`repos: ${res.status} ${res.statusText}`)
  }
  return res.json()
}

async function fetchProfile() {
  const res = await fetch(`${API}/users/${USER}`, { headers })
  if (!res.ok) {
    throw new Error(`profile: ${res.status} ${res.statusText}`)
  }
  return res.json()
}

function pickRepos(repos) {
  return repos
    .filter((r) => !r.fork && !r.archived && !r.disabled)
    .slice(0, 8)
    .map((r) => ({
      name: r.name,
      fullName: r.full_name,
      description: r.description,
      language: r.language,
      stars: r.stargazers_count,
      forks: r.forks_count,
      url: r.html_url,
      updatedAt: r.pushed_at ?? r.updated_at,
    }))
}

async function main() {
  const [repos, profile] = await Promise.all([fetchRepos(), fetchProfile()])
  const picked = pickRepos(repos)
  const totals = {
    publicRepos: profile.public_repos,
    followers: profile.followers,
    following: profile.following,
    stars: picked.reduce((sum, r) => sum + r.stars, 0),
    profileUrl: profile.html_url,
  }

  const banner = `// Auto-generated by scripts/sync-github.mjs at ${new Date().toISOString()} — do not edit by hand`
  const out = `${banner}
export type GitHubRepo = {
  name: string
  fullName: string
  description: string | null
  language: string | null
  stars: number
  forks: number
  url: string
  updatedAt: string
}

export type GitHubTotals = {
  publicRepos: number
  followers: number
  following: number
  stars: number
  profileUrl: string
}

export const githubRepos: GitHubRepo[] = ${JSON.stringify(picked, null, 2)}

export const githubTotals: GitHubTotals = ${JSON.stringify(totals, null, 2)}
`
  writeFileSync('src/data/github.ts', out)
  console.log(`✓ Wrote ${picked.length} repos + totals to src/data/github.ts`)
}

main().catch((err) => {
  console.error('✗ sync-github failed:', err.message)
  process.exit(1)
})
